import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'intro', // Ini file 'docs/intro.md'
    {
      type: 'category',
      label: 'Panduan Server',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: '01-panduan-server',
        },
      ],
    },
    {
      type: 'category',
      link: { type: 'generated-index' },
      label: 'Panduan C++',
      items: [{ type: 'autogenerated', dirName: 'panduan-c++' }],
    },
  ],

  // 'profile' adalah ID sidebar kedua Anda
  profile: [
    {
      type: 'category',
      label: 'About Me', 
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'about_me' }],
    },
    {
      type: 'category',
      label: 'My Research',
      link: { type: 'generated-index' }, 
      items: [{ type: 'autogenerated', dirName: 'my-research' }],
    },
    {
      type: 'category',
      label: 'My Project',
      link: { type: 'generated-index' }, 
      items: [{ type: 'autogenerated', dirName: 'my-project' }],
    },
  ],

  
   
};

export default sidebars;
