import React from 'react';
import Heading from '@theme/Heading';
import styles from './styles.module.css';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Stack from '@mui/material/Stack';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Link from '@docusaurus/Link';

// SVG bawaan template (pasti ada) + yang kamu sudah gunakan
import SvgServer from '@site/static/img/undraw_docusaurus_tree.svg';
import SvgLabelStudio from '@site/static/img/undraw_docusaurus_react.svg';
import SvgAIML from '@site/static/img/undraw_website_builder_re_ii6e.svg';
import SvgDocusaurus from '@site/static/img/undraw_science_re_mnnr.svg';
import SvgCpp from '@site/static/img/undraw_augmented_reality_re_f0qd.svg';

type FeatureItem = {
  title: string;
  link: string;
  Svg: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;
  badge?: string;
  description: JSX.Element;
  cta?: { label: string; to: string };
  tags?: string[];
};

const items: FeatureItem[] = [
  {
    title: 'Panduan VPS & Keamanan',
    link: '/docs/category/panduan-server',
    Svg: SvgServer,
    badge: 'Production Ready',
    tags: ['Ubuntu', 'Nginx', 'Firewall', 'TLS'],
    description: (
      <>
        Setup server dari nol: Nginx, PHP-FPM/MariaDB, UFW, struktur domain, dan
        best-practice hardening. Termasuk template <b>server block</b> dan checklist deploy.
      </>
    ),
    cta: { label: 'Buka Panduan', to: '/docs/category/panduan-server' },
  },
  
  
  {
    title: 'Label Studio & Anotasi',
    link: '/',
    Svg: SvgLabelStudio,
    badge: 'Data-centric',
    tags: ['Nginx', 'Reverse Proxy', 'VPS', 'SSL'],
    description: (
      <>
        Instalasi Label Studio di VPS (reverse proxy Nginx), manajemen proyek anotasi,
        ekspor dataset, dan kiat performa untuk tim labeling.
      </>
    ),
    cta: { label: 'Mulai Anotasi', to: '/' },
  },
  {
    title: 'AI/ML & Multimodal',
    link: '/',
    Svg: SvgAIML,
    badge: 'Riset Aktif',
    tags: ['LangChain', 'Qwen-VL', 'ChatGLM', 'OCR'],
    description: (
      <>
        Blueprint pipeline multimodal: OCR-first, LLM agent, cache gateway berlatensi rendah,
        serta eksperimen koreksi teks visual lintas bahasa.
      </>
    ),
    cta: { label: 'Blueprint Riset', to: '/' },
  },
  {
    title: 'KB Pribadi (Docusaurus)',
    link: '/',
    Svg: SvgDocusaurus,
    badge: 'Docs as Code',
    tags: ['Sidebar', 'MDX Tabs', 'Theme'],
    description: (
      <>
        Pola <i>knowledge base</i> efisien: sidebar autogenerated, halaman summary (generated-index),
        dan komponen React/TSX kustom untuk dokumentasi hidup.
      </>
    ),
    cta: { label: 'Mulai di Sini', to: '/' },
  },
  {
    title: 'C++ Snippets untuk CV/AI',
    link: '/docs/category/panduan-c',
    Svg: SvgCpp,
    badge: 'Praktikal',
    tags: ['Overload', 'Templates', 'Perf'],
    description: (
      <>
        Kumpulan snippet C++ untuk komputasi & CV: overload, pengukuran performa, hingga pola
        interfacing dengan Python/Qt untuk prototyping GUI.
      </>
    ),
    cta: { label: 'Buka Snippets', to: '/docs/category/panduan-c' },
  },
];

/** Single feature card */
function FeatureCard({ Svg, title, badge, description, tags, cta, link }: FeatureItem) {
  return (
    <Paper elevation={0} className={styles.card} component="article">
      <div className={styles.svgWrap}>
        <Svg className={styles.svg} role="img" aria-label={title} />
      </div>

      <div className="text--center">
        <Heading as="h3" className={styles.cardTitle}>
          <Link to={link}>{title}</Link>
        </Heading>

        {badge && <span className={styles.badge}>{badge}</span>}

        <p className={styles.desc}>{description}</p>

        {tags && tags.length > 0 && (
          <Stack
            direction="row"
            justifyContent="center"
            alignItems="center"
            spacing={1}
            className={styles.tags}
          >
            {tags.map((t) => (
              <Chip key={t} label={t} size="small" className={styles.tagChip} />
            ))}
          </Stack>
        )}

        {cta && (
          <Button
            variant="contained"
            className={styles.cta}
            component={Link as any}
            to={cta.to}
          >
            {cta.label}
          </Button>
        )}
      </div>
    </Paper>
  );
}

export default function HomepageFeatures(): JSX.Element {
  return (
    <section className={styles.section}>
      <div className={styles.header}>
        <Heading as="h2">AICS Hub — Toolkit & Playbooks</Heading>
        <p className={styles.subtitle}>
          Semua yang sering kamu bangun: server, Sistem Informasi, anotasi data,
          sampai riset AI/ML — diringkas jadi komponen siap pakai.
        </p>
      </div>

      <Grid container spacing={3}>
        {items.map((it) => (
          <Grid item key={it.title} xs={12} sm={6} md={4}>
            <FeatureCard {...it} />
          </Grid>
        ))}
      </Grid>
    </section>
  );
}
